//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatCanIEat.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe_components
    {
        public int Id { get; set; }
        public string Quantity { get; set; }
        public int Id_recipe { get; set; }
        public int Id_component { get; set; }
        public int Id_unit { get; set; }
    
        public virtual Recipe_header Recipe_header { get; set; }
        public virtual Components Components { get; set; }
        public virtual Units_of_measure Units_of_measure { get; set; }
    }
}
