//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatCanIEat.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Recipe_header = new HashSet<Recipe_header>();
            this.Comments = new HashSet<Comments>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public int Permision { get; set; }
    
        public virtual ICollection<Recipe_header> Recipe_header { get; set; }
        public virtual Permission Permission { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
    }
}
